steps:
  - name: "node:22"
    entrypoint: "npm"
    args: ["ci"]

  - name: "node:22"
    entrypoint: "npm"
    args: ["run", "build"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "app",
        "deploy",
        "app.yaml",
        "--project=$PROJECT_ID",
        "--quiet",
        "--promote",
      ]

timeout: "1200s"
